################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2000 RET & COM Research.
################################################################################

# Change variables here
OBJS = taskman.rdm
modnamesfile = .taskman-modules

# Common rules
include ../../build/header.mk
include ../../build/common.mk

# Individual dependencies
all-dep: dep
all-clean: clean
