################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2000 RET & COM Research.
################################################################################

# This must be defined first
group = libc
subgroup = _posix

# Standard header
include ../../../Build/header.mk

# Change variables here
OBJS = 1.$(O) 1b.$(O) 1c.$(O) 1j.$(O)

# This part shouldn't be changed
include ../../../Build/common.mk

# Individual dependencies
all-dep: dep
all-clean: clean
