# 
# ETH Makefile
#
# x-kernel v3.3
#
# Copyright (c) 1996,1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.2 $
# $Date: 1996/06/03 23:00:24 $

include Files
include $(MAKE_INCLUDE)/Makefile.common
