################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2003 RET & COM Research.
################################################################################

# This must be defined first
group = dev
subgroup = _bus

# Standard header
include ../../../etc/header.mk

# Change variables here
OBJS = pci.$(O)

# This part shouldn't be changed
include ../../../etc/common.mk
