################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2000 RET & COM Research.
################################################################################

# Standard header
include ../../../etc/header.mk

# Change variables here
OBJS = 3c509.rdm ne2k-pci.rdm
modnamesfile = .network-modules

# This part shouldn't be changed
include ../../../etc/common.mk
