################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2000 RET & COM Research.
################################################################################

# Standard header
include ../../etc/header.mk

# Change variables here
OBJS = ext2fs.$(O)
modnamesfile = .ext2fs-modules

# This part shouldn't be changed
include ../../etc/common.mk
