################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2000 RET & COM Research.
################################################################################

# Standard header
include ../../etc/header.mk

# Change variables here
TARGET_LIBS=NONE
OBJS = ext2fs.rdm
modnamesfile = .ext2fs-modules

# This part shouldn't be changed
include ../../etc/common.mk
