################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2000 RET & COM Research.
################################################################################

# Standard header
include ../../../etc/header.mk

# Change variables here
OBJS = rdm.rdm coff.rdm
modnamesfile = $(OUTPATH)/.binfmt-modules

# This part shouldn't be changed
include ../../../etc/common.mk
