################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2000 RET & COM Research.
################################################################################

# Standard header
include ../../build/header.mk

# Change variables here
OBJS = coff.rdm elf.rdm
modnamesfile = $(OUTPATH)/.binfmt-modules

# This part shouldn't be changed
include ../../build/common.mk
