################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2000 RET & COM Research.
################################################################################

# Standard header
include ../../build/header.mk

# Change variables here
TARGET_LIB = NONE
OBJS = syscall.rdm
modnamesfile = $(OUTPATH)/.syscall-modules

# This part shouldn't be changed
include ../../build/common.mk
