# 
# $RCSfile: Makefile,v $
#
# x-kernel v3.3
#
# Copyright (c) 1996,1993,1991,1990  Arizona Board of Regents
#
# $Revision: 1.2 $
# $Date: 1996/06/03 23:02:38 $

include Files

TMP_INCLUDES := -I../util

include $(MAKE_INCLUDE)/Makefile.common
