################################################################################
# Makefile - universal makefile for RadiOS.
# Copyright (c) 2000 RET & COM Research.
################################################################################

# Standard header
include ../../etc/header.mk

# Change variables here
OBJS = tarfs.rdm
modnamesfile = $(OUTPATH)/.tarfs-modules

# This part shouldn't be changed
include ../../etc/common.mk
